### ISSUE TITLE
Image __init__ fails on at least one gif

### ISSUE THREAD

**Issue by TristanTrim** [joshua-stone/DerPyBooru#10]
```
>>> from derpibooru import Search
>>> for im in Search():
...  pass
... 
Traceback (most recent call last):
  File "/usr/lib/python3.4/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/home/trist/ponyAquisitionProgram/derpibooru/search.py", line 206, in __next__
    return Image(next(self._search))
  File "/home/trist/ponyAquisitionProgram/derpibooru/image.py", line 49, in __init__
    setattr(self, "webm", self.representations["webm"])
KeyError: 'webm'
```

**Comment by TristanTrim** [comment]
I'm recommending 12c461b be pulled to master.

**Comment by BytewaveMLP** [comment]
The library maintainer appears to be inactive, so I've taken up maintaining the library on [my personal fork](https://github.com/BytewaveMLP/DerPyBooru). I've already committed the update which fixes this, and plan on publishing it to PyPi under a different name if it doesn't violate anything.

**Comment by joshua-stone** [comment]
I've removed support for mp4/webm representations as they no longer appear to be exposed by Derpibooru's API.
