### ISSUE TITLE
id_number depricated in Derpibooru's API

### ISSUE THREAD

**Issue by JoeyH3** [joshua-stone/DerPyBooru#13]
Hello!

A recent update to Derpibooru has deprecated the "id_number" attribute in their API for images, and replaced it simply with "id". I wanted to bring this to your attention as images.py seems to reference this (possibly other things as well), and this may be causing some issues.

Cheers!

**Comment by Nuke928** [comment]
I made a pull-request about this https://github.com/joshua-stone/DerPyBooru/pull/12 but I think the maintainer is dead.

**Comment by luckydonald** [comment]
Bump?
Someone with the power to merge?
@liamwhite @joshua-stone?

**Comment by joshua-stone** [comment]
Hey everyone, sorry for not maintaining this code when things broke. I've pushed a version update to PyPi, so please let me know if you find any more breakage.

**Comment by luckydonald** [comment]
Yay!

**Comment by joshua-stone** [comment]
Closing this issue as the library was updated as part of issue #14
