### ISSUE TITLE
Check for current status

### ISSUE THREAD

**Issue by DonaldTsang** [joshua-stone/DerPyBooru#23]
See https://github.com/Sibusten/derpibooru-downloader/issues/30 for API and web changes.

**Comment by joshua-stone** [comment]
@DonaldTsang There have been changes merged in response to the API change as of #24

**Comment by DonaldTsang** [comment]
Please close this issue once the full code refactoring is complete, thank you.

**Comment by personifire** [comment]
I believe the version on PyPI is still using the old API, which derpibooru is removing on the 31st of this month. A new release would be appreciated.

**Comment by personifire** [comment]
@joshua-stone

**Comment by DonaldTsang** [comment]
@joshua-stone please confirm and close the issue if it has been fixed.

**Comment by joshua-stone** [comment]
A new version has been pushed to PyPi. If it works for you, then I may close this issue.

**Comment by personifire** [comment]
Now that the old API is now offline, and requests using this library seem to still be working, I think it's safe to say that everything is alright.
