### ISSUE TITLE
Use Filter

### ISSUE THREAD

**Issue by luckydonald** [joshua-stone/DerPyBooru#8]
API says  
> Search endpoints are controlled by the current user's **filter** (or the default, if no key is supplied); if you wish to using a custom **filter**, you can use the "**filter_id**" parameter.

For example the [`public filter with the id 118851`](https://derpibooru.org/filters/118851) ([as json](https://derpibooru.org/filters/118851.json)) can be used in a search query as following:
[`https://derpibooru.org/search.json?q=*&filter_id=118851`](https://derpibooru.org/search.json?q=*&filter_id=118851) where `q=*` search for everything (wildcard)

Trying around showed:
 - the filter is ignored in normal browser searches (if `.json` is omitted)
 - if `filter_id` is present anywhere, `key` is ignored.
 - if the filter is private, `key` must be present to display the filter metadata [derpiboo.ru/filters/118854](http://derpibooru.org/filters/118854)
     - but does **not prevent** you from **using** it, you can search with **private** filters **without** the **key**. [private filter 118854 search](https://derpibooru.org/search.json?q=*&filter_id=118854)
 - really nice is that the user [json of the filter](https://derpibooru.org/filters/118851.json) contains a **user id** instead of the username.
    - So you can't mistake **a** Background pony with [**the** Background pony](https://derpibooru.org/profiles/Background+Pony) (which I created accidentally today... :sweat:)

**Comment by Nuke928** [comment]
I highly approve. Having to use keys has turned out to be quite annoying.

**Comment by liamwhite** [comment]
That's correct.
```ruby
  def load_filter
    if using_api? && params[:filter_id].present?
      @current_filter ||= Filter.for(nil, params[:filter_id])
    else
      @current_filter ||= Filter.for(current_user, session[:filter_id])
    end
  end
```

**Comment by luckydonald** [comment]
What is correct?
Also, what does that code snippet? (and what language is it? looks bit like ruby/rails from what I stumbled across)

**Comment by liamwhite** [comment]
That's the code snippet from the derpibooru source code related to API filter usage. Your observations laid out in the first post match what the code does.

**Comment by luckydonald** [comment]
@liamwhite So you are a coding team member there? Or is it now open source and I completely missed it? :cold_sweat:

**Comment by liamwhite** [comment]
I have had source code access for almost a year now. The code itself is currently not publically available and will remain so for the forseeable future, but I am more than happy to share code that wouldn't impinge on the efforts of the admins to maintain control of the site.

**Comment by luckydonald** [comment]
Maybe you can share some insight why I can't get the tag changes to work [example 1](https://derpibooru.org/images/1034163/tag_changes.json), [example 0](https://derpibooru.org/images/0/tag_changes.json)

**Comment by liamwhite** [comment]
The API for tag and source changes was leaking sensitive user information (user IPs!) and so was stemmed when I discovered this. We have not yet created a fix.

**Comment by luckydonald** [comment]
Also, can you share what replacements are done in order to come from a [artist:foo-bar] tag name to the /tags/artist-colon-foo-dash-bar slug?

**Comment by liamwhite** [comment]
This discussion is getting off topic.

**Comment by luckydonald** [comment]
Tell me where to continue it, please.

**Comment by liamwhite** [comment]
byte[] on irc.ponychat.net #derpibooru (I will be afk for some time after responding, please send me a PM with your questions and I'll answer them when I'm back.)

**Comment by luckydonald** [comment]
@6 relates to this

**Comment by luckydonald** [comment]
I have something working here. I'll see if I can PR tomorrow.

**Comment by luckydonald** [comment]
@liamwhite
Is filter_id always a number?

**Comment by liamwhite** [comment]
Yes.

**Comment by luckydonald** [comment]
I'll add that to #9

**Comment by luckydonald** [comment]
So it just needs a Version bump on PyPi.

**Comment by luckydonald** [comment]
Is it?
